import { Link } from 'react-router-dom'

function About() {
  return (
    <div className="about-page">
        <div className="about-left">
            <div className="about-rank">#22 in the world</div>
            <div className="about-stat">
                <p className="stat-number">33,743,793</p>
                <p className="stat-label">Followers</p>
            </div>
            <div className="about-stat">
                <p className="stat-number">71,777,916</p>
                <p className="stat-label">Monthly Listeners</p>
            </div>
            <div className="about-cities">
                <p className="city-row"><span>London, GB</span><span>1,555,378 listeners</span></p>
                <p className="city-row"><span>Chicago, US</span><span>1,059,979 listeners</span></p>
                <p className="city-row"><span>Los Angeles, US</span><span>1,009,367 listeners</span></p>
                <p className="city-row"><span>New York City, US</span><span>898,863 listeners</span></p>
                <p className="city-row"><span>Sydney, AU</span><span>887,039 listeners</span></p>
            </div>
            <div className="about-socials">
                <a href="https://www.instagram.com/kanyewest" target="_blank">Instagram</a>
                <a href="https://x.com/kanyewest" target="_blank">X</a>
                <a href="https://en.wikipedia.org/wiki/Kanye_West" target="_blank">Wikipedia</a>
            </div>
        </div>
        <div className="about-right">
            <p className="about-bio">One of the most influential, critically lauded, and controversial artists of the early 21st century, American rapper and producer Kanye West has gone from hip-hop beatmaker to worldwide hitmaker with a wildly successful solo career that counted an unbroken string of chart-topping, multi-platinum albums and nearly two-dozen Grammy Awards. His early-2000s production work quickly led to a major-label recording contract, yielding a classic trilogy comprised of 2004's The College Dropout, 2005's Late Registration, and 2007's Graduation. With each successive album, he pushed the boundaries of hip-hop and soon entered a new phase of artistry with game changers such as 2008's 808s & Heartbreak, 2010's widely regarded magnum opus My Beautiful Dark Twisted Fantasy, and 2013's industrial-leaning foray Yeezus. Celebrity, tabloid headlines, and a changing artistic vision informed much of his next era, as the trappings of fame and inner turmoil became the focus of chart-toppers such as The Life of Pablo and Ye. He even released a gospel album, Jesus Is King, in 2019. As his outspoken personality and political statements began to eclipse his music into the 2020s, he still managed to top the charts and garner accolades with 2020's exploratory Donda. In 2023, West joined forces with Ty Dolla $ign to form a new project, ¥$ and quickly releasing chapters of a trilogy in 2024 that included the albums Vultures 1 and Vultures 2.

A proud and vocal Chicagoan, West was actually born in Atlanta, moving to the Windy City with his English professor mother after his parents split when he was three years old. One of his major inspirations, Donda West helped shape young Kanye, taking him to China in the late '80s on education exchange and establishing a strong base that made him a top pupil in high school. However, his music dreams would eventually eclipse academics and he dropped out of college, setting the stage for his best-selling school trilogy. With guidance from local producer No I.D., West went on to learn the finer points of studio production, programming, and sampling, the latter technique becoming a hallmark of his early work. 

He first got his foot in the industry door in the late '90s, doing quite a bit of noteworthy production work for the likes of Jermaine Dupri, Foxy Brown, Mase, and Goodie Mob. However, it was West's work for the Roc-A-Fella label at the dawn of the new millennium that took his career to the next level. Alongside fellow fresh talent Just Blaze, West became one of the Roc's go-to producers, consistently delivering hot tracks to album after album. His star turn came on Jay-Z's classic The Blueprint (2001) with album standouts "Takeover" and "Izzo (H.O.V.A.)." Both songs showcased West's signature beatmaking style at the time, which was largely sample-based; in these cases, the former track appropriated snippets of the Doors' "Five to One," while the latter sampled the Jackson 5's "I Want You Back." 

More high-profile productions followed, and before long, word spread that West was going to release an album of his own, on which he planned to rap as well as produce. Unfortunately, that effort was a long time coming, pushed back repeatedly until a car crash in 2002 threatened to end his solo career before it even started. The accident left him with a jaw wired shut during his weeks-long recovery. He capitalized on the traumatic experience by using it as the inspiration for "Through the Wire" (and its corresponding video), which would later become the lead single for his debut album, 2004's The College Dropout. As the album was further delayed, West continued to create big hits for the likes of Talib Kweli ("Get By"), Ludacris ("Stand Up"), Jay-Z ("'03 Bonnie & Clyde"), and Alicia Keys ("You Don't Know My Name"). Then, just as "Through the Wire" was breaking big-time at the tail-end of 2003, another West song caught fire, a collaboration with Twista and actor Jamie Foxx called "Slow Jamz," which gave the rapper/producer two simultaneously ubiquitous singles and a much-anticipated debut album. As with so many of West's songs, the singles were driven by somewhat recognizable sample-based hooks: Chaka Khan's "Through the Fire" in the case of "Through the Wire" and Luther Vandross' "A House Is Not a Home" in the case of "Slow Jamz." During these early days, West paired his beats with tongue-twisting raps and outspoken confidence. With a backpack and brightly colored polo shirt, his dapper fashion sense set him apart from many of his peers, while his attitude often came across as boastful and egotistical. This flamboyance made for good press, something that West enjoyed, for better or worse, throughout the course of his career. 

In the wake of his breakout success, West earned a whopping ten nominations at the 47th annual Grammy Awards in early 2005. The College Dropout won the Best Rap Album award, "Jesus Walks" won Best Rap Song, and a songwriting credit on "You Don't Know My Name" for Best R&B Song award was shared with Alicia Keys and Harold Lilly. Later that year, West released his second solo album, Late Registration, which spawned a series of hit singles ("Diamonds in Sierra Leone," "Gold Digger," "Heard 'Em Say," "Touch the Sky"). The album topped the charts, as did the "Gold Digger" single, and Late Registration eventually won a Grammy for Rap Album of the Year. West's production work continued more or less unabated during this time; particularly noteworthy were hits for Twista ("Overnight Celebrity"), Janet Jackson ("I Want You"), Brandy ("Talk About Our Love"), the Game ("Dreams"), Common ("Go!"), and Keyshia Cole ("I Changed My Mind"). West also founded his own label, GOOD Music ("Getting Out Our Dreams"), in conjunction with Sony BMG. The label's inaugural release was John Legend's Get Lifted (2004), followed one year later by Common's Be. In addition to all of his studio work, West also toured internationally in support of Late Registration and released Late Orchestration: Live at Abbey Road Studios (2006) in commemoration.

After retreating from the spotlight for some time, West returned to the forefront of the music world in 2007 with a series of album releases. Consequence's Don't Quit Your Day Job and Common's Finding Forever, both released by GOOD, were chiefly produced by West; the latter proved to be particularly popular, topping the album chart upon its release in July. And then there was West's third solo album, Graduation, which was promoted well in advance of its September 11 release (a memorable date that pitted Kanye against 50 Cent, who in one interview swore he would quit music if his own album, Curtis, wasn't the top-seller). A pair of singles -- "Can't Tell Me Nothing" and "Stronger," the latter an interpolation of Daft Punk's 2001 single "Harder, Better, Faster, Stronger" -- led the promotional push. It became his third consecutive chart-topping album, and its success culminated in eight Grammy nominations. West was the victor in four of the categories, and he performed two songs during the ceremony, including Late Registration's "Hey Mama," chosen in honor of his recently deceased mother. That loss, compounded by a breakup with his fiancée, informed 2008's genre-busting landmark 808s & Heartbreak, a major change of pace that saw West singing most of his emotionally pained lyrics with the assistance of Auto-Tune. The album went platinum, spawning Top Three hits "Love Lockdown" and "Heartless," while influencing a generation of young rappers wanting to tap into their emotional sides. West toured internationally, even returning to China in 2008 for a stop on his Glow in the Dark Tour. However, after a headline-grabbing turn at the 2009 MTV Video Awards involving Taylor Swift, West retreated from the spotlight to record another album.

In 2010, West emerged with his fifth work, My Beautiful Dark Twisted Fantasy, which marked the start of a new era for the artist, one focused on fame, sex, and opulent production. Recorded in Hawaii, the star-studded set recruited a staggering number of guest vocal spots from the likes of Kid Cudi, Elton John, Rihanna, Bon Iver, Rick Ross, and RZA. Preceded by the bombastic, King Crimson-sampling single "Power," Fantasy also included the Grammy-winning "All of the Lights," fan favorite "Runaway," and "Monster," which featured a star-making turn by a young Nicki Minaj. A sprawling and audacious statement, it debuted at number one on the Billboard 200, won a Grammy for Best Rap Album, and also went multi-platinum. While the album was still hot, West recorded the aggressive and boast-heavy Watch the Throne with Jay-Z and numerous producers and songwriters. Billed as a set by the Throne, it was released in August 2011 and entered the Billboard Top 200 chart at number one. A trio of hit singles -- "Otis," "No Church in the Wild," and "Ni**as in Paris" -- climbed the charts and each won Grammy Awards, capping a dominant run for the rapper that resulted in 21 Grammys within just eight years.

In September 2012, he released the GOOD Music collaboration album Cruel Summer, which featured artists such as Big Sean, Pusha T, and Lifted. Four singles ("Mercy," "Cold," "New Flow," and "Clique") were released as promotion for the record. Toward the end of the year, there were rumblings from acclaimed producers that a new album would emerge soon. These murmurs were soon confirmed when West himself announced that he was working on his sixth album with the likes of Daft Punk, King L., Justin Vernon, Rick Rubin, Chief Keef, and many more contributing. As one of the most eagerly anticipated albums of 2013, the angry and aggressive Yeezus was released to rapturous reviews from critics. Incorporating industrial-electronic touches, screamed vocals, and soaring gospel, West touched upon both controversial and sensitive topics while delivering an astonishing and bold record, described as his most confrontational and bravest album to date. Despite leaking days before its official release, Yeezus still sold almost 327,000 copies during its first week and singles "Black Skinhead" and "Bound 2" were certified platinum while "New Slaves" received a Grammy nomination.

The year 2013 also proved to be a personal milestone for West, as he became a father for the first time with partner Kim Kardashian. The following year, he announced a new album and released "Only One" featuring Paul McCartney, which, like his 2015 single "FourFiveSeconds" with McCartney and Rihanna, remained a non-LP release. Later, he announced another, different album, titled So Help Me God, which later turned to SWISH, then Waves, and finally The Life of Pablo. The album was released on Valentine's Day 2016 and shot to the top of the Billboard 200. The guest list for the platinum-selling effort included Chance the Rapper, Kid Cudi, Young Thug, Chris Brown, Sia, the Weeknd, French Montana, Frank Ocean, Post Malone, Jay-Z, and many more. In the age of streaming and direct artist-to-fan access, West took advantage of the technology and continued to tinker with the album even after it was released, tweaking production, guest verses, and even lyrics.

During the promotion of Pablo, West canceled the final dates of his revolutionary Saint Pablo Tour -- during which he performed from a "floating" stage suspended above the pit -- and was hospitalized for psychiatric observation. He retreated from the spotlight for nearly a year and re-emerged in 2017 to begin recording material for his next album -- as well as production for artists on his GOOD Music label -- at a studio in Jackson Hole, Wyoming. While there, he also continued to court controversy with his political views and public statements made via social media. Amidst the headline flurry, he released a pair of singles in April 2018: "Lift Yourself" and "Ye vs. the People" with T.I. The following month, West delivered the first of the "Wyoming Sessions" studio productions with Pusha T's critically acclaimed, Grammy-nominated Daytona. A week later, West released his eighth official set, Ye, which featured appearances by Kid Cudi, Ty Dolla $ign, and Nicki Minaj, as well as production by Mike Dean, Che Pope, Francis and the Lights, and Benny Blanco. Singles "Yikes" and "All Mine" were both certified platinum and hovered around the Top Ten on the Hot 100. The third installment of the series arrived the next week, marking the debut of the collaborative project Kids See Ghosts, a duo formed by West and Cudi. Kids See Ghosts featured Pusha T, Mos Def, and Ty Dolla $ign, as well as samples of Louis Prima and Kurt Cobain. West's Wyoming Sessions were completed with the release of Nas' Nasir and Teyana Taylor's K.T.S.E., and he received a nomination for Producer of the Year at the 2019 Grammy Awards.

Following the flurry of activity in Wyoming, West released a pair of singles to close out the year. While the drug- and lust-filled "XTCY" was more of a B-side, its follow-up "I Love It" with Lil Pump took off on the charts and became a viral hit, boosted by a surreal music video and equally quirky live television performances. Certified double platinum, the song was West's highest charting on the Hot 100 since 2015's "FourFiveSeconds." Riding the momentum of "I Love It," West announced that another album was imminent. Like the pre-Pablo SWISH and Waves buildup, the proposed Yandhi -- a sequel to Yeezus -- never materialized and, in 2019, West revealed the album would be titled Jesus Is King. To promote the effort, he expanded his "Sunday Service" gospel revival events across the U.S., playing early versions of the album to fans in Detroit, Chicago, and New York City. Issued that October, Jesus Is King became West's ninth straight number one studio album as a headliner. Singles "Closed on Sunday" and "Follow God" landed the rapper on multiple international charts, while the latter was certified gold in the U.S. A companion set from West's Sunday Service Choir, Jesus Is Born, arrived on Christmas Day 2019. Although West's vocals did not appear on the album, the crew intertwined their takes on tracks like "Ultralight Beam" and "Father Stretch My Hands" with their versions of beloved gospel songs by the Clark Sisters and Reverend Timothy Wright.

Recording for West's tenth album, Donda, began in early 2020. Named after his late mother, the release of Donda was surrounded by the same chaotic energy that encircled everything West was involved with at the time. Release dates were announced and pushed back, and after a listening party at Atlanta's Mercedes Benz Stadium in late July of 2021, West took up residence in one of the stadium's locker rooms to continue mixing and finalizing the recording of the album. Another listening party was scheduled around a new, tentative release date. The Grammy-nominated set finally arrived in August and entered number one in over a dozen countries. A sequel, Donda 2, appeared in February of 2022, exclusively available as part of the Stem Player, a remix device and streaming platform developed by British company Kano Computing in collaboration with West. However, because the release was not made available to purchase or stream outside of the device, it was deemed ineligible for the Billboard charts. Featuring the likes of Baby Keem, Migos, Jack Harlow, Alicia Keys, and many more, it reportedly managed to sell thousands of players, earning West millions. For the rest of the year, despite attempts to maintain a lower profile -- he pulled out of Coachella and Rolling Loud headline slots at the last minute -- West remained in the headlines with his continued controversial and inflammatory statements. In 2023, West joined forces with rapper Ty Dolla $ign to form ¥$. The duo released debut single "Vultures" in November of that year. They slowly leaked out information about the project in the lead-up to an oft-delayed debut full-length Vultures 1 before finally releasing it in February of 2024. The album, which featured guest appearances from a number of famous artists including Lil Durk, Freddie Gibbs, James Blake, and many others, debuted at the top of the Billboard 200 chart. Though ¥$ initially claimed they would release subsequent chapters Vultures 2 and Vultures 3 as a trilogy at the rate of one album per month, it would be August of 2024 when Vultures 2 finally materialized. The album again included a host of guest appearances, this time making space for collaborations from Lil Wayne, Young Thug, Desiigner, and Kodak Black, just to name a few. ~ Andy Kellman & Neil Z. Yeung, Rovi
            </p>
        </div>
    </div>
  )
}

export default About